import { MultiFileUploader } from '@/components/file-upload/multi-file-uploader';
import { Inter } from 'next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Image converter</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <h1 className={'text-align-center py-30'}>Image converter</h1>
                <div className={'w-100 min-height-100 position-center'}>
                    <MultiFileUploader/>
                </div>
            </main>
        </>
    );
}
